"""
AI Tactical Director (Red Force Agent)

Analyzes Blue Force radar coverage and dynamically generates adversarial
scenarios that exploit weaknesses in the sensor network.

Features:
    1. Coverage Map Generation: 2D detection probability grid
    2. Blind Zone Detection: Contiguous regions with no radar coverage
    3. Attack Planning: Terrain-following routes through blind zones
    4. Jammer Deployment: Optimal DRFM jammer placement
    5. Difficulty Scaling: Easy / Medium / Hard

Architecture:
    NetworkManager → AIDirector.analyze_coverage() → BlindZones
                   → AIDirector.plan_attack() → AttackPlan

References:
    - Blackman, S. "Multiple-Target Tracking with Radar Applications", 1986
    - Skolnik, M.I. "Radar Handbook", 3rd Ed., Ch. 24 (ECM)
    - Developed by Mehmet Gümüş (github.com/SpaceEngineerSS)
"""

from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Dict, List, Optional, Tuple

import numpy as np

# Speed of light [m/s]
C_LIGHT = 299_792_458.0


class Difficulty(Enum):
    """Scenario difficulty levels."""
    EASY = auto()
    MEDIUM = auto()
    HARD = auto()


@dataclass
class BlindZone:
    """
    A contiguous region with no radar coverage.

    Attributes:
        center_xy: Center of the blind zone [m]
        cells: List of (row, col) grid cells in this zone
        area_km2: Approximate area [km²]
        min_pd: Minimum detection probability in the zone
    """
    center_xy: np.ndarray
    cells: List[Tuple[int, int]]
    area_km2: float
    min_pd: float


@dataclass
class WaypointRoute:
    """
    A route through low-coverage areas.

    Attributes:
        waypoints: List of [x, y] positions [m]
        total_exposure: Sum of Pd along the route
        route_length_m: Total path length [m]
    """
    waypoints: List[np.ndarray]
    total_exposure: float
    route_length_m: float


@dataclass
class AttackPlan:
    """
    Red Force attack plan generated by the AI Director.

    Attributes:
        difficulty: Scenario difficulty
        target_routes: Planned target flight paths
        jammer_positions: Optimal jammer deployment locations
        attack_azimuth_deg: Primary attack direction [deg]
        description: Human-readable plan description
    """
    difficulty: Difficulty
    target_routes: List[WaypointRoute] = field(default_factory=list)
    jammer_positions: List[np.ndarray] = field(default_factory=list)
    attack_azimuth_deg: float = 0.0
    description: str = ""


class AIDirector:
    """
    AI Tactical Director — Red Force Agent.

    Analyzes Blue Force radar network coverage and generates adversarial
    scenarios that exploit coverage gaps, GDOP weaknesses, and sensor
    limitations.

    Example:
        >>> from src.simulation.network_manager import NetworkManager
        >>> nm = NetworkManager()
        >>> nm.register_node("R1", np.array([0, 0]))
        >>> nm.register_node("R2", np.array([50000, 0]))
        >>> director = AIDirector(grid_size_m=100000, grid_resolution=100)
        >>> coverage = director.analyze_coverage(nm, detection_range_m=80000)
        >>> zones = director.find_blind_zones(coverage)
        >>> plan = director.plan_attack(nm, coverage, Difficulty.HARD)

    Reference: Blackman (1986); Skolnik, "Radar Handbook", Ch. 24
    """

    def __init__(
        self,
        grid_size_m: float = 200_000.0,
        grid_resolution: int = 100,
        seed: int = 42,
    ) -> None:
        """
        Initialize AI Director.

        Args:
            grid_size_m: Coverage map extent [m] (centered at origin)
            grid_resolution: Grid points per axis
            seed: RNG seed for reproducibility
        """
        self.grid_size_m = grid_size_m
        self.grid_resolution = grid_resolution
        self.rng = np.random.default_rng(seed)

        # Grid setup
        half = grid_size_m / 2
        self._x_edges = np.linspace(-half, half, grid_resolution)
        self._y_edges = np.linspace(-half, half, grid_resolution)
        self._cell_size_m = grid_size_m / grid_resolution

    def analyze_coverage(
        self,
        radar_positions: List[np.ndarray],
        detection_range_m: float = 80_000.0,
        min_snr_db: float = 13.0,
    ) -> np.ndarray:
        """
        Generate 2D detection probability coverage map.

        For each grid cell, computes detection probability based on
        range to nearest radar:
            Pd(r) = exp(-0.5 * (r / R_det)^4)  [simplified Swerling-1]

        Args:
            radar_positions: List of [x, y] radar positions [m]
            detection_range_m: Maximum detection range [m]
            min_snr_db: Minimum SNR for detection [dB]

        Returns:
            [grid_res, grid_res] detection probability map (0-1)

        Reference: Skolnik, Ch. 2 (Radar Equation)
        """
        coverage = np.zeros((self.grid_resolution, self.grid_resolution))

        xx, yy = np.meshgrid(self._x_edges, self._y_edges)

        for radar_pos in radar_positions:
            dx = xx - radar_pos[0]
            dy = yy - radar_pos[1]
            r = np.sqrt(dx**2 + dy**2)

            # Detection probability vs range (Swerling-1 approximation)
            # Pd decays with r^4 (radar equation: SNR ∝ 1/r^4)
            pd_radar = np.exp(-0.5 * (r / detection_range_m) ** 4)

            # Max fusion: any radar detecting is sufficient
            coverage = np.maximum(coverage, pd_radar)

        return coverage

    def find_blind_zones(
        self,
        coverage: np.ndarray,
        pd_threshold: float = 0.3,
        min_cells: int = 4,
    ) -> List[BlindZone]:
        """
        Identify contiguous blind zones (low-coverage regions).

        Uses flood-fill to find connected regions where Pd < threshold.

        Args:
            coverage: 2D detection probability map
            pd_threshold: Maximum Pd to consider "blind"
            min_cells: Minimum cells to form a valid blind zone

        Returns:
            List of BlindZone objects sorted by area (largest first)
        """
        mask = coverage < pd_threshold
        visited = np.zeros_like(mask, dtype=bool)
        zones: List[BlindZone] = []

        for i in range(self.grid_resolution):
            for j in range(self.grid_resolution):
                if mask[i, j] and not visited[i, j]:
                    # Flood fill
                    cells = self._flood_fill(mask, visited, i, j)
                    if len(cells) >= min_cells:
                        # Compute zone properties
                        rows = [c[0] for c in cells]
                        cols = [c[1] for c in cells]
                        center_x = self._x_edges[int(np.mean(cols))]
                        center_y = self._y_edges[int(np.mean(rows))]
                        area_km2 = len(cells) * (self._cell_size_m / 1000) ** 2
                        min_pd = float(np.min(coverage[mask]))

                        zones.append(BlindZone(
                            center_xy=np.array([center_x, center_y]),
                            cells=cells,
                            area_km2=area_km2,
                            min_pd=min_pd,
                        ))

        # Sort by area (largest first)
        zones.sort(key=lambda z: z.area_km2, reverse=True)
        return zones

    def plan_attack(
        self,
        radar_positions: List[np.ndarray],
        coverage: np.ndarray,
        difficulty: Difficulty = Difficulty.MEDIUM,
        n_targets: int = 1,
    ) -> AttackPlan:
        """
        Generate an adversarial attack plan.

        Args:
            radar_positions: List of [x, y] radar positions [m]
            coverage: 2D detection probability map
            difficulty: Scenario difficulty
            n_targets: Number of attack targets to generate

        Returns:
            AttackPlan with routes, jammers, and description

        Difficulty levels:
            EASY: Random straight-line approach
            MEDIUM: Terrain-following through lowest-Pd corridor
            HARD: Coordinated multi-axis with DRFM jammers
        """
        blind_zones = self.find_blind_zones(coverage)
        plan = AttackPlan(difficulty=difficulty)

        if difficulty == Difficulty.EASY:
            plan.description = "Random approach — no EW support"
            for _ in range(n_targets):
                route = self._random_route()
                plan.target_routes.append(route)

        elif difficulty == Difficulty.MEDIUM:
            plan.description = "Terrain-following through lowest-Pd corridor"
            for _ in range(n_targets):
                route = self._low_pd_route(coverage)
                plan.target_routes.append(route)

        elif difficulty == Difficulty.HARD:
            plan.description = "Coordinated multi-axis attack with DRFM jammers"

            # Deploy jammers at blind zone edges facing radars
            if blind_zones:
                for zone in blind_zones[:2]:  # Max 2 jammers
                    plan.jammer_positions.append(zone.center_xy.copy())

            # Route targets through blind zones
            for _ in range(n_targets):
                route = self._low_pd_route(coverage)
                plan.target_routes.append(route)

            # Determine primary attack azimuth
            if blind_zones:
                center = blind_zones[0].center_xy
                plan.attack_azimuth_deg = float(np.degrees(
                    np.arctan2(center[1], center[0])
                ))

        return plan

    def find_entry_point(
        self,
        coverage: np.ndarray,
        approach_range_m: float = 100_000.0,
    ) -> Optional[np.ndarray]:
        """
        Find the best entry point on the coverage boundary for an attacker.

        Scans the perimeter of the coverage map at approach_range_m and
        returns the azimuth with the lowest detection probability.

        Args:
            coverage: 2D detection probability map
            approach_range_m: Distance from origin to start approach [m]

        Returns:
            [x, y] position of the best entry point, or None
        """
        best_pd = 1.0
        best_pos = None

        n_angles = 72  # 5° steps
        for k in range(n_angles):
            theta = 2.0 * np.pi * k / n_angles
            x = approach_range_m * np.cos(theta)
            y = approach_range_m * np.sin(theta)

            # Map to grid indices
            ix = int((x + self.grid_size_m / 2) / self._cell_size_m)
            iy = int((y + self.grid_size_m / 2) / self._cell_size_m)
            ix = np.clip(ix, 0, self.grid_resolution - 1)
            iy = np.clip(iy, 0, self.grid_resolution - 1)

            pd = coverage[iy, ix]
            if pd < best_pd:
                best_pd = pd
                best_pos = np.array([x, y])

        return best_pos

    # ─── PRIVATE METHODS ───

    def _flood_fill(
        self,
        mask: np.ndarray,
        visited: np.ndarray,
        start_r: int,
        start_c: int,
    ) -> List[Tuple[int, int]]:
        """Iterative flood fill for connected-component labeling."""
        stack = [(start_r, start_c)]
        cells: List[Tuple[int, int]] = []

        while stack:
            r, col = stack.pop()
            if r < 0 or r >= mask.shape[0] or col < 0 or col >= mask.shape[1]:
                continue
            if visited[r, col] or not mask[r, col]:
                continue
            visited[r, col] = True
            cells.append((r, col))
            stack.extend([(r - 1, col), (r + 1, col), (r, col - 1), (r, col + 1)])

        return cells

    def _random_route(self) -> WaypointRoute:
        """Generate a random straight-line approach route."""
        angle = self.rng.uniform(0, 2 * np.pi)
        start = np.array([
            self.grid_size_m / 2 * np.cos(angle),
            self.grid_size_m / 2 * np.sin(angle),
        ])
        end = np.array([0.0, 0.0])  # Aim for origin

        n_waypoints = 10
        waypoints = [
            start + (end - start) * t / (n_waypoints - 1)
            for t in range(n_waypoints)
        ]

        length = float(np.linalg.norm(end - start))
        return WaypointRoute(
            waypoints=waypoints,
            total_exposure=float("nan"),  # Not computed for random
            route_length_m=length,
        )

    def _low_pd_route(self, coverage: np.ndarray) -> WaypointRoute:
        """
        Generate a route through the lowest-Pd corridor.

        Uses greedy navigation: at each step, move toward the origin
        through the cell with the lowest Pd.

        Reference: A*-inspired cost = Pd(cell) minimization
        """
        # Find entry point
        entry = self.find_entry_point(coverage)
        if entry is None:
            return self._random_route()

        waypoints = [entry.copy()]
        current = entry.copy()
        total_exposure = 0.0
        total_length = 0.0

        target = np.array([0.0, 0.0])
        step_size = self._cell_size_m * 2

        for _ in range(50):  # Max 50 steps
            if np.linalg.norm(current - target) < step_size:
                waypoints.append(target.copy())
                break

            # Direction toward target
            direction = target - current
            direction = direction / np.linalg.norm(direction)

            # Evaluate 5 candidate directions (±30° fan)
            best_cost = float("inf")
            best_next = current + direction * step_size

            for angle_offset in [-0.5, -0.25, 0.0, 0.25, 0.5]:
                rot = np.array([
                    [np.cos(angle_offset), -np.sin(angle_offset)],
                    [np.sin(angle_offset), np.cos(angle_offset)],
                ])
                candidate_dir = rot @ direction
                candidate = current + candidate_dir * step_size

                # Map to grid
                ix = int((candidate[0] + self.grid_size_m / 2) / self._cell_size_m)
                iy = int((candidate[1] + self.grid_size_m / 2) / self._cell_size_m)
                ix = np.clip(ix, 0, self.grid_resolution - 1)
                iy = np.clip(iy, 0, self.grid_resolution - 1)

                pd = coverage[iy, ix]
                # Cost = Pd + distance penalty
                dist_to_target = np.linalg.norm(candidate - target)
                cost = pd + 0.3 * dist_to_target / self.grid_size_m

                if cost < best_cost:
                    best_cost = cost
                    best_next = candidate

            total_length += np.linalg.norm(best_next - current)
            current = best_next
            waypoints.append(current.copy())

            # Accumulate exposure
            ix = int((current[0] + self.grid_size_m / 2) / self._cell_size_m)
            iy = int((current[1] + self.grid_size_m / 2) / self._cell_size_m)
            ix = np.clip(ix, 0, self.grid_resolution - 1)
            iy = np.clip(iy, 0, self.grid_resolution - 1)
            total_exposure += coverage[iy, ix]

        return WaypointRoute(
            waypoints=waypoints,
            total_exposure=total_exposure,
            route_length_m=total_length,
        )
